### ISSUE TITLE
Not working on Linux (Ubuntu 20.04.2 LTS)

### ISSUE THREAD

**Issue by JeremyStarTM** [PolyMarsDev/Flappuccino#20]
Hi, I'm running GNU/LInux Ubuntu 20.04.2 LTS with the KDE Plasma Desktop.
I ran from source and installed pygame. But when I run Flappuccino, this error comes up (full log output):
**jeremystartm@StarPC:~/Flappuccino$ python3 main.py**
_pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from .player import Player
ImportError: attempted relative import with no known parent package_

Info: **Bold** = Command | _Italic_ = Command output

**Comment by firefish111** [comment]
The fact that you chose Ubuntu as your distribution says everything.

**Comment by firefish111** [comment]
Also, you can buy triple Backtick's ~~dont look at edits, I hate autocorrect~~ above and below to do this
```
Monospace
J
H
H
G
```

**Comment by ghost** [comment]
> Hi, I'm running GNU/LInux Ubuntu 20.04.2 LTS with the KDE Plasma Desktop.
> I ran from source and installed pygame. But when I run Flappuccino, this error comes up (full log output):
> **jeremystartm@StarPC:~/Flappuccino$ python3 main.py**
> _pygame 2.0.1 (SDL 2.0.14, Python 3.8.5) Hello from the pygame community. https://www.pygame.org/contribute.html Traceback (most recent call last): File "main.py", line 4, in from .player import Player ImportError: attempted relative import with no known parent package_
> 
> Info: **Bold** = Command | _Italic_ = Command output

literally search up how to install pygame on ubuntu dont make an issue on the github

**Comment by JeremyStarTM** [comment]
@phoebe-leong, thanks for not helping me at all. The thing wont even say anything when pygame is not installed with pip3.

**Comment by firefish111** [comment]
well try installing it locally then, locally in the directory

**Comment by ghost** [comment]
> @phoebe-leong, thanks for not helping me at all. The thing wont even say anything when pygame is not installed with pip3.

you might have to directly download pygame from [the github](https://github.com/pygame/pygame/releases).

**Comment by JeremyStarTM** [comment]
Okay, thanks @phoebe-leong, I could try that one.

**Comment by firefish111** [comment]
no u
