### ISSUE TITLE
a performance improvement and cleaner code 

### ISSUE THREAD

**Issue by Emc2356** [PolyMarsDev/Flappuccino#22]
so i wanted to merge my fork with this branch and couldnt make a pull request so i am here making a ticket. so i basically improved FPS and made the code cleaner with more comments were i understood what was going on

**Comment by firefish111** [comment]
Its easy to make a pr, using gh, the GitHub CLI. Add long as there copy is a clone of the repo, and not downloaded, just by running `gh pr create` and say yes when it asks you to fork the repo, you should be fine

**Comment by Emc2356** [comment]
what not working for me idk why probably doing something wrong first time improving someone's code
