### ISSUE TITLE
Wrong link?

### ISSUE THREAD

**Issue by 1hiking** [PolyMarsDev/Flappuccino#5]
The link to the itch.io sends you to https://polymars.itch.io/cursor-custodian instead of https://polymars.itch.io/flappuccino

**Comment by hikingc** [comment]
Found out someone already filled this, however gonna keep my issue open :^)

**Comment by ghost** [comment]
> Found out someone already filled this, however gonna keep my issue open :^)

check #4, its a pull by me talking about the same thing

**Comment by PolyMarsDev** [comment]
oops, thanks for letting me know! I just merged the PR
