### ISSUE TITLE
Could not import .player from player [ISSUE CLOSED]

### ISSUE THREAD

**Issue by TTR-maniac** [PolyMarsDev/Flappuccino#6]
info:
pygame 2.0.1 (SDL 2.0.14, Python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from .player import Player
ImportError: attempted relative import with no known parent package

**Comment by TTR-maniac** [comment]
I even put main in the same dierectory as data

**Comment by pablouser1** [comment]
Can be fixed if you remove the initial "." from some of the imports of main.py

**Comment by TTR-maniac** [comment]
> Can be fixed if you remove the initial "." from some of the imports of main.py

Thanks :)

**Comment by TTR-maniac** [comment]
nevermind heres what happend
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/1751760/Desktop/Flappuccino-main/data/main.py", line 4, in <module>
    from player import Player
  File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player\__init__.py", line 14, in <module>
    from player.layout_impl import layout
  File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player\layout_impl.py", line 10, in <module>
    from pyramid.compat import text_, string_types
ModuleNotFoundError: No module named 'pyramid.compat'

**Comment by TTR-maniac** [comment]
can you fork this project and fix the syntaxs that I have?

**Comment by pablouser1** [comment]
> nevermind heres what happend
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
> File "c:/Users/1751760/Desktop/Flappuccino-main/data/main.py", line 4, in
> from player import Player
> File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player__init__.py", line 14, in
> from player.layout_impl import layout
> File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player\layout_impl.py", line 10, in
> from pyramid.compat import text_, string_types
> ModuleNotFoundError: No module named 'pyramid.compat'

That's probably because you have [this](https://pypi.org/project/player) package installed, which is interfering with our player.py, it hasn't been updated since 2013 so I think you have installed it by mistake

**Comment by TTR-maniac** [comment]
> > nevermind heres what happend
> > Hello from the pygame community. https://www.pygame.org/contribute.html
> > Traceback (most recent call last):
> > File "c:/Users/1751760/Desktop/Flappuccino-main/data/main.py", line 4, in
> > from player import Player
> > File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player__init__.py", line 14, in
> > from player.layout_impl import layout
> > File "C:\users\1751760\appdata\local\programs\python\python38\lib\site-packages\player\layout_impl.py", line 10, in
> > from pyramid.compat import text_, string_types
> > ModuleNotFoundError: No module named 'pyramid.compat'
> 
> That's probably because you have [this](https://pypi.org/project/player) package installed, which is interfering with our player.py, it hasn't been updated since 2013 so I think you have installed it by mistake

I Did not

**Comment by TTR-maniac** [comment]
/data/main.py
pygame 2.0.1 (SDL 2.0.14, Python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/1751760/Desktop/Flappuccino-main/data/main.py", line 4, in <module>
    from .player import Player
ImportError: attempted relative import with no known parent package

**Comment by TTR-maniac** [comment]
Just help me...!!!!!

**Comment by TTR-maniac** [comment]
import pygame, sys, time, random, colorsys, math
from pygame.math import Vector2
from pygame.locals import *
from .player import Player
from background import Background
from button import Button
from .bean import Bean
from .utils import clamp
from .utils import checkCollisions
These are the imports if you can fix this and tell me how I can fix it I owe you

**Comment by red-socks294** [comment]
Okay. Seems like you need to put all the .py files in the same direcony as Data.

**Comment by Finxx1** [comment]
it seems like you have a pip package messing with ```player.py```. I would uninstall all packages except for ```pygame```, ```pip```, and ```setuptools```. You also should get rid of all the ```.```'s in the imports.

**Comment by red-socks294** [comment]
> 
> 
> import pygame, sys, time, random, colorsys, math
> from pygame.math import Vector2
> from pygame.locals import *
> from .player import Player
> from background import Background
> from button import Button
> from .bean import Bean
> from .utils import clamp
> from .utils import checkCollisions
> These are the imports if you can fix this and tell me how I can fix it I owe you

omg like remove the .s from the Imports...........

**Comment by mandar1jn** [comment]
Could you close the issue instead of putting it in the title?
